import urllib.request

url = "https://game.denver69.fun/Jtv/EiWIY4/Playlist.m3u"

try:
    req = urllib.request.Request(
        url, headers={"User-Agent": "Mozilla/5.0"}
    )
    with urllib.request.urlopen(req) as response:
        content = response.read().decode("utf-8")

    lines = content.splitlines()
    cleaned_lines = []

    for line in lines:
        # ਜੇ ਲਾਈਨ ਵਿੱਚ billed-msg ਹੈ, ਤਾਂ ਉਸ ਨੂੰ ਬਦલ ਕੇ ਆਪਣਾ ਨਾਂ ਲਿਖ ਦਿਓ
        if "billed-msg" in line:
            # ਪੁਰਾਣੇ ਮੈਸੇਜ ਨੂੰ ਬਦਲ ਕੇ 'Playlist generated by Khehra' ਕਰ ਦਿਓ
            line = line.split("billed-msg=")[0] + 'billed-msg="Playlist generated by Khehra"'
        
        cleaned_lines.append(line)

    # ਸਾਫ਼ ਕੀਤੀ ਫ਼ਾਈਲ ਨੂੰ ਸੇਵ ਕਰੋ
    with open("channels.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(cleaned_lines))

    print("Success! Message updated.")

except Exception as e:
    print(f"Error: {e}")
    
