import urllib.request

url = "https://game.denver69.fun/Jtv/EiWIY4/Playlist.m3u"
file_path = "channels.m3u"  # GitHub ਰਿਪੋਜ਼ਟਰੀ ਵਿੱਚ ਸੇਵ ਹੋਣ ਵਾਲੀ ਫ਼ਾਈਲ

try:
    req = urllib.request.Request(
        url, headers={"User-Agent": "Mozilla/5.0"}
    )
    with urllib.request.urlopen(req) as response:
        content = response.read().decode("utf-8")

    lines = content.splitlines()
    cleaned_lines = []

    for line in lines:
        # ਜੇ ਲਾਈਨ ਵਿੱਚ 'billed-msg' ਹੈ, ਤਾਂ ਉਸ ਨੂੰ ਪੂਰੀ ਤਰ੍ਹਾਂ ਹਟਾ ਕੇ ਆਪਣੀ ਨਵੀਂ ਲਾਈਨ ਪਾ ਦਿਓ
        if "billed-msg" in line:
            new_line = (
                line.split("billed-msg=")[0]
                + 'billed-msg="Playlist Generated by Khehra"'
            )
            cleaned_lines.append(new_line)
        else:
            cleaned_lines.append(line)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(cleaned_lines))

    print("Success! Playlist updated and saved.")

except Exception as e:
    print(f"Error: {e}")
