name: Update M3U Playlist

on:
  schedule:
    - cron: '*/5 * * * *' # ਹਰ 5 ਮਿੰਟ ਬਾਅਦ ਆਟੋਮੈਟਿਕ ਚੱਲੇਗੀ
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: python script.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add channels.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update and clean M3U playlist" && git push)
